### ISSUE TITLE
make all matlab command line output informative

### ISSUE THREAD

**Issue by SharpWave** [SharpWave/scopix#18]
get rid of my lazy iterator counts

**Comment by SharpWave** [comment]
mostly done? We could make a thing that doesn't spam the screen so bad -- I think there are a few progress bar functions floating around

**Comment by SharpWave** [comment]
OK now I need to get rid of all of the spam; would be nice to see where batch runs are.  Maybe 1 or 2 lines of output per function in Tenaspis

**Comment by nkinsky** [comment]
I think having some sort of progress bar that lets you know the status of
Tenaspis on each run would be sweet (though probably not that easy to
implement).

**Comment by SharpWave** [comment]
This still needs to be addressed...

**Comment by nkinsky** [comment]
I have something that I use now for CalculatePlaceFields...it's a progress
bar function I stole from online that works well, the only caveat is it
requires dumping a small text file into your current directory each time,
but it does work with parfor loops.  The function is ProgressBar (in my
repo) and you can look at sample code under CalculatePlacefields in my
branch (Nat-PF-adjust-branch), starting around line 173.
