### ISSUE TITLE
use the mosaic code to automate the initial step of doing the disc smoothing and saving the file in the right directory

### ISSUE THREAD

**Issue by SharpWave** [SharpWave/scopix#23]

**Comment by nkinsky** [comment]
Can help with this, just let me know.  It's pretty easy but I could probably save you about an hour when you get to it.

**Comment by SharpWave** [comment]
I will check out what has been done but until Inscopix updates this to work with the most current Matlab release it's not going in production Tenaspis.

**Comment by nkinsky** [comment]
Agreed.  We have working code to do batch process a bunch of movies this
way, but otherwise it is not worth it.
