### ISSUE TITLE
infile format

### ISSUE THREAD

**Issue by MaBeWi** [SharpWave/scopix#37]
Hi, I am very interested in trying out the Tenaspis script, but I have trouble 
getting the script to read my h5 infile. 

Would it be possible for you to upload a demo movie in the h5 format 
that works with the script? I converted a tif stack to h5, but I cant get Tenaspis to work with this infile.

I would really appreciate you help! 

Best regards, Mattis Wigestrand

**Comment by SharpWave** [comment]
Hi Mattis,

I uploaded an .h5 file of our mouse recordings (~10 minutes, 20 Hz) that
should work with Tenaspis.

https://drive.google.com/file/d/0Bxf-G_s5VcRuS1pHYm5aVlhQb0k/view?usp=sharing

-Dave

**Comment by MaBeWi** [comment]
Great. Thank you so much! 
-Mattis
