### ISSUE TITLE
T2 crash

### ISSUE THREAD

**Issue by wmau** [SharpWave/scopix#39]
Crashes at MakeTransients for at least two movies.

Error message: 
Error using checkCC (line 12)
CC must contain the following fields: Connectivity, ImageSize, NumObjects, and PixelIdxList.

Error in regionprops (line 180)
        checkCC(CC);

Error in MakeTransients (line 47)
    stats = regionprops(cc{i},'MinorAxisLength');

Error in Tenaspis2 (line 26)
MakeTransients('DFF.h5',0);

**Comment by wmau** [comment]
Possible fix around line 102: 

% exit if no blobs found
if isempty(newlist)
    PeakPix = [];
    cc.NumObjects = 0;
    cc.PixelIdxList = [];
*\*    cc.ImageSize = size(frame);
    cc.Connectivity = 0; **
    %display('no blobs detected');
    return;
end

Issue is being caused by the if statement exiting the function before assigning the structure fields ImageSize and Connectivity. Then regionprops crashes because it checks for those fields in MakeTransients. 

Currently running T2 to test fix.

**Comment by SharpWave** [comment]
Yeah that's where I thought it would be, in Segment Frame.

**Comment by wmau** [comment]
Fix worked.

**Comment by SharpWave** [comment]
push please
