### ISSUE TITLE
T2 neuron mask bug

### ISSUE THREAD

**Issue by wmau** [SharpWave/scopix#42]
Nat, 

Are you sure the bugfix you committed on 3/24 is good? It looks like mask_multi_image_reg takes a tif as its first input but your change makes that input a .mat file. 

Will

**Comment by nkinsky** [comment]
Will,

The input is supposed to be a .mat file containing the base session neuron
mask.  I've updated the function comments to reflect this.

Just tested it on 2 sessions and fixed another bug.  Hopefully all is good
now.

Nat

**Comment by wmau** [comment]
Ah I found the source of the problem. There are two copies of that function in my path -- one in your repo and one in Dave's. I deleted the one in yours and it's fixed now.

**Comment by nkinsky** [comment]
Yes.  However, the bug I fixed is one I'm sure I've fixed before.  I'll do
some more testing today to make sure that all is good, but I think an older
version of the image registration stuff may have been copied over when all
the Tenaspis stuff got combined into Dave's repo.
