### ISSUE TITLE
Error in AutoMergeClu

### ISSUE THREAD

**Issue by wmau** [SharpWave/scopix#50]
In line 104 of AutoMergeClu, 

% Exclusion criteria - skip to next cluster if the cluster grows
        % too much
        [a,ia,ib] = intersect(PixelList{i},PixelList{cidx});

It is possible for there to be no common values between PixelList{i} and PixelList{cidx}, causing the line after it to fail.

**Comment by wmau** [comment]
Fixed -- see https://github.com/SharpWave/TENASPIS/commit/1a8f396ada4dcb0c820cd8797159c60dd5d6a604

Simply added an if statement that will move on to the next cluster to merge if no intersection between the two clusters-to-merge are detected. Revert this commit if deemed unsatisfactory. Perhaps consider lowering the max value of MinPixelDist in MakeNeurons. This issue arose at MinPixelDist == 6.

**Comment by SharpWave** [comment]
with current modifications to this script this issue is effectively obsolete
